### ISSUE TITLE
Team Research & Development Project Discussion and Assignment Work

### ISSUE THREAD

**Issue by tarikuk** [M-ismail-UH/Team-Research-and-Development#1]
![histogram_star_rating](https://github.com/user-attachments/assets/73eff413-46de-476b-9218-aa82a976d4bc)

**Comment by kashif-shahzad-ai** [comment]
![3333](https://github.com/user-attachments/assets/d49ed006-bf40-4cb6-9aad-3cc4ba521461)

**Comment by Aktheysay** [comment]
i think Kashif graphs seems bit more realistic but i think we need to do more digging

**Comment by kashif-shahzad-ai** [comment]
> ![3333](https://private-user-images.githubusercontent.com/184252841/387873062-d49ed006-bf40-4cb6-9aad-3cc4ba521461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNTk1ODgsIm5iZiI6MTczMjA1OTI4OCwicGF0aCI6Ii8xODQyNTI4NDEvMzg3ODczMDYyLWQ0OWVkMDA2LWJmNDAtNGNiNi05YWFkLTNjYzRiYTUyMTQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQyMzM0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWIxYTg4NDhiNTQxY2MxODQ2MWZlZjdkOTc3NGZjYWNmYTYyNmI3YjAzMjlhZGViZjM4MmMyM2JhY2ZlNGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VRpl9TVEg7x-A0YNvdnaVPOuFmKPsCQ8aloL-GfhtJY)

I have created this histogram using dependant variable that is starRating.

**Comment by kashif-shahzad-ai** [comment]
But I recommend that we will arrange a meeting in which everyone can explain their visualisation.
And pls share your work here as well, thanks

**Comment by ammmar-hash** [comment]
@kashif-shahzad-ai What does the distribution of cuisines or categories suggest about the variety of star ratings?

**Comment by ammmar-hash** [comment]
> But I recommend that we will arrange a meeting in which everyone can explain their visualisation. And pls share your work here as well, thanks

sure

**Comment by tarikuk** [comment]
@kashif-shahzad-ai  your graphic bit seem good but i think both graphs showing same results, but both have same idea in the end so we can use one.  My question is still there like do you guys think we have choose right variable and does it fulfil the requirements?

**Comment by Aktheysay** [comment]
> But I recommend that we will arrange a meeting in which everyone can explain their visualisation.
> 
> And pls share your work here as well, thanks

Yes, we can all join and discuss this further more

**Comment by kashif-shahzad-ai** [comment]
> What does the distribution of cuisines or categories suggest about the variety of star ratings?

In our dataset, we have different type of cuisines or we say categories which are upto 15. Each category has different starRating,  as we know Style or type of cuisine is our independant variable, and starRating is dependant variable.

**Comment by tarikuk** [comment]
shaka laka boom boom

**Comment by kashif-shahzad-ai** [comment]
And we have to make boxplot as well, and I am sure everyone is working on that.

**Comment by M-ismail-UH** [comment]
Great job on overlaying the histogram with the normal curve! It provides a clear visualization of the distribution. To make it even better, we could add a boxplot for a complementary view of the data's spread and potential outliers.

**Comment by kashif-shahzad-ai** [comment]
[reseach_question_presentation_template (1).pptx](https://github.com/user-attachments/files/17882402/reseach_question_presentation_template.1.pptx)
