### ISSUE TITLE
I have attached histogram_ chart

### ISSUE THREAD

**Issue by tarikuk** [M-ismail-UH/Team-Research-and-Development#3]
I have attached histogram_ chart and i am adding further data into it, @ammmar-hash @Aktheysay   guys the data you will need for the report related to histogram would be in this file which i will complete soon, take from this word file and @kashif-shahzad-ai  please do check the file see if everything is good so far, THANKS.

**Comment by Aktheysay** [comment]
?

**Comment by Aktheysay** [comment]
Okay we'll see

**Comment by ammmar-hash** [comment]
okay we working on it

**Comment by kashif-shahzad-ai** [comment]
We have to analyse normal curve, in my opinion, normal curve overlay does not follow the shape of the underlying data, so for our analysis we use the non-parametric test for correlation that does not assume normality: Spearman’s Rho or Kendal’s Tau

**Comment by tarikuk** [comment]
i have done everything i am going to close this ticket, thanks for everyone
