### ISSUE TITLE
REPORT 

### ISSUE THREAD

**Issue by Aktheysay** [M-ismail-UH/Team-Research-and-Development#6]
If I’ve missed anything, please let me know so we can ensure everything is covered.
(formatting is yet to done)

**Comment by Aktheysay** [comment]
[report.docx](https://github.com/user-attachments/files/17896076/report.docx)

**Comment by M-ismail-UH** [comment]
lemme take a look it briefly and I will let you know. btw great job.

**Comment by Aktheysay** [comment]
@ammmar-hash have you seen the updated report?

**Comment by ammmar-hash** [comment]
@Aktheysay yes i update the report file
